# Generated by Django 4.2.11 on 2025-06-02 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('fitness&nutrition', 'Fitness&Nutrition')], max_length=255)),
                ('question_en', models.TextField()),
                ('question_ar', models.TextField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('how_to_play', models.TextField()),
                ('time', models.SmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercises/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercises/videos/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('fitness', 'Fitness'), ('nutrition', 'Nutrition'), ('fitness&nutrition', 'Fitness&Nutrition')], max_length=255)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_plan_requests', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255)),
                ('name_ar', models.CharField(max_length=255)),
                ('advice_en', models.TextField(blank=True, null=True)),
                ('advice_ar', models.TextField(blank=True, null=True)),
                ('days', models.IntegerField()),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('daily_time', models.CharField(max_length=255)),
                ('kalories', models.IntegerField()),
                ('plan_goal_en', models.CharField(max_length=50)),
                ('plan_goal_ar', models.CharField(max_length=50)),
                ('weeks', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='plans/images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_plan', to='programs.sport')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targeted_muscles', to='programs.exercise')),
                ('muscle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muscle', to='programs.muscle')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_en', models.TextField()),
                ('answer_ar', models.TextField()),
                ('plan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='programs.planrequest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.coachquestion')),
            ],
            options={
                'unique_together': {('plan_request', 'question')},
            },
        ),
        migrations.CreateModel(
            name='PlanSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('plan', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ExerciseDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.PositiveSmallIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps_en', models.CharField(max_length=255)),
                ('reps_ar', models.CharField(max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_detail', to='programs.exercise')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='programs.plan')),
            ],
            options={
                'unique_together': {('plan', 'exercise', 'week', 'day')},
            },
        ),
    ]
