# Generated by Django 4.2.11 on 2025-07-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_nutritionplan_mealdetail_fooditem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plansubscription',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='nutritionPlan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programs.nutritionplan'),
            preserve_default=False,
        ),
    ]
