# Generated by Django 4.2.11 on 2025-07-17 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_alter_plansubscription_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubscription',
            name='nutritionPlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.nutritionplan'),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.plan'),
        ),
    ]
